source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '10.3'

target "aspace" do
    pod 'Firebase/Core'
    pod 'RealmSwift'
    pod 'Alamofire', '~> 4.4'
    pod 'Mapbox-iOS-SDK', '~> 3.6'
    pod 'SearchTextField'
    pod 'LGButton'
    pod 'PMAlertController'
    pod 'PureLayout'
end
